services:
  obsidianrag:
    image: obsidianrag
    build:
      context: .
      dockerfile: ObsidianRag/Dockerfile
    environment:
      - ConnectionString=Host=postgres;Database=obsidianrag_db;Username=postgres;Password=postgres
      - ObsidianStoragePath=/app/data
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - /mnt/d/Storage/CountNeuroBrain:/app/data:ro

  postgres:
    build:
      context: ./pgvector
      dockerfile: Dockerfile
    container_name: obsidianrag-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: obsidianrag_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  